### PR TITLE
GameController, and PageService start  for game.jsp

### PR DESCRIPTION
**Pull request by DylanHolmesDH**
- Added GamePageController.java
- Added GamePageUpdateService.java

### CODE REVIEW

**Comment by Emperorlou** [comment]
It says it has conflicts...

**Comment by DylanHolmesDH** [comment]
Says the conflicts are in test.jsp which I just deleted....

**Comment by Emperorlou** [comment]
Damn...

**Comment by Emperorlou** [comment]
Don't think I can fix that from my phone. Can you revert it?

**Comment by DylanHolmesDH** [comment]
Fixed, should now be able to merge.

**Pull request merged**
